### ISSUE TITLE
Add support for L4T 32.4.4

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson#127]

**Comment by acostach** [comment]
Support merged in https://github.com/balena-os/balena-jetson/pull/126, versions after BalenaOS v2.67.3 will now include L4T 32.4.4

**Comment by acostach** [comment]
@sjdrc we've updated the jetson repository to L4T 32.4.4 but haven't received any dtb updates for the blackboard from you in https://github.com/balena-os/balena-jetson/issues/72 Currently the blackboard still has the 28.2 dtb so we cannot deploy it with the 32.4.4 kernel. If you wish to update your devices please PR a new 32.4.4 dtb.

**Comment by sjdrc** [comment]
Hey, thanks for the heads up. We don't plan to update our devices at this point.
