### ISSUE TITLE
Request for update to balenaOS for Jetson Nano

### ISSUE THREAD

**Issue by kenna-smith** [balena-os/balena-jetson#131]
Customer has requested an update of balenaOS from current version (2.56.0) to at least v2.61.0 in order to take advantage of the `io.balena.features.journal-logs` feature (described [here](https://www.balena.io/docs/learn/develop/multicontainer/#labels)) on their NVIDIA Jetson Nano.

**Comment by acostach** [comment]
ack, @kenna-smith can you confirm please if the release is needed for the Nano SD-card or for the Nano eMMC?

**Comment by acostach** [comment]
Done, both the SD and eMMC images have been deployed in production at v2.67.
