### ISSUE TITLE
[PhotonNX/NX] Boot bins need updating after 32.4.4 upgrade

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson#136]
boot binary in the spi eeprom needs updating, most likely due to bsp firmwares/dtb changes in 32.4.4

Reported for Photon NX and Xavier NX

**Comment by acostach** [comment]
@pgils the boot issue after HUP should be fixed in the latest build 2.67.3+rev5, let me know in case the problem persists

**Comment by pgils** [comment]
I just tested updating `photon-nx` from `2.58.6+rev5` to `2.67.3+rev5` and it works fine now. Thanks @acostach !

**Comment by acostach** [comment]
Perfect, thanks for confirming.
