### ISSUE TITLE
Health check incorrectly reports high temperature alarms

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-jetson#142]
The health check on a customer's Nvidia Jetson Xavier NX Devkit SD-CARD with 8GB memory shows that thermal zone 4 (PMIC) is high in temperature. However, NVIDIA themselves (https://forums.developer.nvidia.com/t/thermal-zone4-reports-100-degree-celcius/44422/6?u=rakshak.talwar) say that the zone 4 temperature always reports as 100 degrees C, regardless of its actual value.

We need to confirm that this is the case, and if such modify the health checks not to report this as an error.

**Comment by xginn8** [comment]
if this can/should be ignored, we can add any relevant slugs to the temperature check blacklist: https://github.com/balena-io/device-diagnostics/blob/master/scripts/checks.sh#L303-L317

**Comment by acostach** [comment]
Fix is merged in device-diagnostics and available in production.
