### ISSUE TITLE
Update L4T 32.5/32.5.1

### ISSUE THREAD

**Issue by dremsol** [balena-os/balena-jetson#150]

**Comment by alexgg** [comment]
A pre-requisite for this is the upstream `meta-tegra` layer (https://github.com/OE4T/meta-tegra) updating

**Comment by acostach** [comment]
JF tickets updated for Jetson Nano 32.5.1 release at v2.82.11

**Comment by acostach** [comment]
Devices have been updated to L4T 32.5.1 and images were deployed.

@compiaffe can you please PR the Aetina N310 and N510 community board dtbs on L4T 32.5.1 so we can release their images too?

**Comment by compiaffe** [comment]
@acostach  Sorry to revive an old thread. I'd like to get the n510 and n310 to the newest balena release. Which version or commit should I target?

FYI @hejsil
