### ISSUE TITLE
Customer request for QCA6174 WiFi firmware on TX2

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-jetson#151]
We would like to use QCA6174 based wifi devices and would like the firmware to be added to the base image for the TX2 board. The firmware is open source and included in the upstream Linux kernel sources.

Adding these in manually works as expected.

* linux-firmware-ath10k-qca6174
* linux-firmware-ath10k
* linux-firmware-qca

Specifically the firmwares we are needing to use:

/lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin
/lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
/lib/firmware/qca/nvm_usb_00000302.bin
/lib/firmware/qca/rampatch_usb_00000302.bin

sourced test firmware from : https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/

**Comment by acostach** [comment]
Fix in production
