### ISSUE TITLE
Add CTI Photon TX2 NX device type

### ISSUE THREAD

**Issue by ClintHaerinck** [balena-os/balena-jetson#207]
It would be great to have the CTI Photon TX2 NX as device type. I have the dtb's for JP4.5.1

**Comment by acostach** [comment]
Sure! I think you can try to simply PR the dtb first, with a descriptive name like for instance cti_photon_tx2_nx_32_5_1.dtb etc, I'll include it and release the image and then you can set it in the device configuration table of a board that uses the default TX2 NX image and see if it works as expected. The TX2 NX uses u-boot just like the TX2 which, as opposed to the Xavier, allows for using custom dtbs without reflashing partitions, etc.

**Comment by acostach** [comment]
Alternatively you can PR the device support as community by creating a coffee file, a yocto machine and the dtb.

**Comment by ClintHaerinck** [comment]
I will make a PR now, is it possible to change the default dtb of the machine after the PR is merged? When not, please wait to merge the device type

**Comment by acostach** [comment]
The default dtb can be changed by creating another PR after the original one is merged.

**Comment by acostach** [comment]
Thank you for your PRs @ClintHaerinck, I'll close this ticket now that the device is available in production too.
