### ISSUE TITLE
Allow switching dtb for tx2 nx in the dashboard

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson#214]
We will have to allow this feature for the TX2 NX in the sv and in the dashboard.

**Comment by acostach** [comment]
As well as for the upcoming community devices: tx2-nx and tx2-4gb

**Comment by acostach** [comment]
PRed in:
- https://github.com/balena-os/balena-supervisor/pull/1777
- https://github.com/balena-io/open-balena-api/pull/744

**Comment by ClintHaerinck** [comment]
Is this feature working in production?

**Comment by acostach** [comment]
@ClintHaerinck should work starting with supervisor v12.10.3, can you try update to that version

**Comment by acostach** [comment]
Fixed for the TX2 NX in release v2.88.4+rev1
