### ISSUE TITLE
Release 2.85.xx for jn30b-nano

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-jetson#231]
User is asking when this version will be made available for their Auvidea JN30B Nano device as it is available for Jetson Nanos (jetson-nano slug)

**Comment by ClintHaerinck** [comment]
When doing an update from v2.67.3+rev2 to v2.82.11+rev8 I'm getting following error:
```
Dec 03 15:49:50 localhost systemd[1]: balena-supervisor.service: Job balena-supervisor.service/start failed with result 'dependency'.
Dec 03 15:49:50 localhost systemd[1]: Dependency failed for Balena supervisor.
Dec 03 15:49:50 localhost systemd[1]: prepare-openvpn.service: Job prepare-openvpn.service/start failed with result 'dependency'.
Dec 03 15:49:50 localhost systemd[1]: openvpn.service: Job openvpn.service/start failed with result 'dependency'.
Dec 03 15:49:50 localhost systemd[1]: Dependency failed for OpenVPN.
Dec 03 15:49:50 localhost systemd[1]: Dependency failed for Prepare OpenVPN.
Dec 03 15:49:50 localhost systemd[1]: Failed to start OS configuration device key service.
Dec 03 15:49:50 localhost systemd[1]: os-config-devicekey.service: Failed with result 'exit-code'.
Dec 03 15:49:50 localhost systemd[1]: os-config-devicekey.service: Main process exited, code=exited, status=127/n/a
```
And because of this the Balena engine isn't booting anymore

**Comment by ClintHaerinck** [comment]
I managed to update till balenaOS v2.82.11+rev2 but when doing the update to v2.82.11+rev8 I'm getting the above error.
The supervisor version is v12.11.16

**Comment by acostach** [comment]
Hi @ClintHaerinck , indeed, the os-config binary fails to run due to a rust library linking issue. This doesn't seem to affect the development variant of the same revision however. We are currently investigating the root cause of this problem and based on what we find will decide how to proceed and will let you know.

**Comment by acostach** [comment]
Hi @ClintHaerinck , can you please try the latest image version v2.82.11+rev11?

**Comment by ClintHaerinck** [comment]
Thanks, issue with version v2.82.11 solved!

**Comment by acostach** [comment]
Release v2.88.1 is available in production, JF has been updated.
