### ISSUE TITLE
Nvidia Jetson Nano 4GB Dev Kit Balena OS not available 

### ISSUE THREAD

**Issue by ruturajshinde2807** [balena-os/balena-jetson#236]
I have Nvidia Jetson Nano 4GB Dev kit with me but it seems that there is no Balena OS available for this device.

**Comment by acostach** [comment]
Hi @ruturajshinde2807 , the Jetson Nano SD-CARD image works on the 4GB devkit, provided that the module in your devkit has an sd-card.

**Comment by acostach** [comment]
@ruturajshinde2807 I'll close this for now, feel free to re-open if needed.
