### ISSUE TITLE
Request for v2.98.45 or newer on AGX Dev Kit

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-jetson#361]
See: https://github.com/balena-os/balena-jetson/issues/353
Depends-on: https://github.com/balena-os/balena-jetson/pull/354

> We use both the Xavier NX SD-Card and the eMMC. Our two fleets are a combination of these, including the AGX Dev Kit. I recognize this does not help prioritize. We use the SD-CARD for development, so testing and deployment would be done there first, but our "production" systems are the AGX Dev Kit at the moment.

**Comment by acostach** [comment]
v2.99.27+rev1 deploy has been triggered in production for the Jetson Xavier AGX. This version adds NFS V4 support.
