### ISSUE TITLE
[L4T 32.1] - logo is displaced to the upper left

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson#4]
This happens with both nano and xavier

**Comment by floion** [comment]
@shaunmulligan I think we can release to production with this issue and have a look at it afterwards.
What do you think?

**Comment by shaunmulligan** [comment]
@floion I think for an initial release it should be fine

**Comment by floion** [comment]
Thanks. Will deploy it now

**Comment by acostach** [comment]
This issue is fixed for jetson-nano in production version 2.43.0, which is based on L4T 32.2

If this will still occur for another board from the lineup, a new ticket will be opened for that specific board.
