### ISSUE TITLE
TX2: Update to  32.7.3 and test new DRAM (PCN209140)

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-jetson#413]
Order and test the DRAM change on TX2 devkits (requires patch update to  32.7.3)

**Comment by acostach** [comment]
Part number will stay the same the same, the new DRAM part number is SKH 161-0434-100 H9HCNNNBKUMLXR-NEE. See JF thread for complete detals

**Comment by acostach** [comment]
Asked in upstream issue https://github.com/OE4T/meta-tegra/issues/1121 if this BSP update is on meta-tegra's roadmap.

**Comment by acostach** [comment]
v2.108.9+rev1 uses L4T 32.7.3 and the attached support tickets have been updated.
