### ISSUE TITLE
Support for Orin NX requested

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson#415]

**Comment by acostach** [comment]
Linked pattern https://jel.ly.fish/pattern-customer-interest-nvidia-jetson-orin-nx-series-c5208c1

**Comment by acostach** [comment]
BOOTAA64.efi isn't loaded by default on 35.1.0, question asked in upstream https://forums.developer.nvidia.com/t/load-bootaa64-efi-from-a-different-fat-partition/229379

**Comment by acostach** [comment]
cc @mikhail-vl, I recall you were interested in testing this? ^

**Comment by acostach** [comment]
Support for the Orin NX is being added in https://github.com/balena-os/balena-jetson-orin/pull/147

**Comment by acostach** [comment]
The Orin NX 16GB module in Xavier NX Devkit (NVME boot) is now available in balena-cloud at v2.114.0

**Comment by mikhail-vl** [comment]
@acostach Thank you. We are using 32Gb and may explore 16Gb as they are available now in balenaCloud.
