### ISSUE TITLE
Add support for Intel Wifi addon

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-jetson#6]
The exact wifi addon card is linked in the forums

https://forums.balena.io/t/support-for-jetson-nano/5962/12

**Comment by zrzka** [comment]
It's AC 8265 NGW M.2. It's officially recommended by Nvidia, better statement, it's officially used in almost all Nvidia's Nano tutorials.

**Comment by acostach** [comment]
This issue is fixed and is available in production release 2.43.0
