### ISSUE TITLE
Production release for CTI Photon Nano with chronyd fix

### ISSUE THREAD

**Issue by ClintHaerinck** [balena-os/balena-jetson#624]
Is it possible provide a new BalenaOS release?

The Jetson Nano eMMC device type has an image at v2.112.13 for example. The CTI Photon Nano is still at 2.103.2

**Comment by acostach** [comment]
Hi @ClintHaerinck , I deployed v3.0.11 for the Photon Nano. Please note that the Nano eMMC Devkit is maintained and tested by us, whereas the CTI Photon Nano is a community supported device-type. We don't run testing on it and only do releases as requested by users. Let us know how the image works for you

**Comment by acostach** [comment]
Feel free to re-open if anything else needed
